http:
  listner:
    host: "0.0.0.0"
    port: "9083"
    path: "/getRoutes"
  requester:
    host: "localhost"
    port: "9081"
    routesPath: "/travelOnTipCall/routes"
    schedulesPath: "/travelOnTipCall/schedules"